Add configure for UPC backtracing.  On some systems (e.g. freebsd) and extra library (execinfo) must be placed on the UPC link line for backtrace and backtrace_symbl functions.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -692,6 +692,7 @@ ENABLE_CLANG_REWRITER
 ENABLE_CLANG_UPC2C
 ENABLE_CLANG_UPC_RUNTIME
 LIBUPC_LINK_SCRIPT
+LIBUPC_ENABLE_BACKTRACE
 ENABLE_OPTIMIZED
 ENABLE_PROFILING
 DISABLE_ASSERTIONS
@@ -1426,6 +1427,9 @@ Optional Features:
                           will define the UPC shared section as a no load
                           section on targets where this feature is supported
                           (requires GNU LD)
+  --enable-upc-backtrace  Enable UPC backtrace; Enable stack frame backtrace
+                          report when UPC run-time fatal errors occur or by
+                          user request (via signal)
   --enable-optimized      Compile with optimizations enabled (default is NO)
   --enable-profiling      Compile with profiling enabled (default is NO)
   --enable-assertions     Compile with assertion checks enabled (default is
@@ -5418,6 +5422,146 @@ _ACEOF
   LIBUPC_LINK_SCRIPT=1
 else
   LIBUPC_LINK_SCRIPT=0
+fi
+
+
+{ echo "$as_me:$LINENO: checking for UPC backtrace support" >&5
+echo $ECHO_N "checking for UPC backtrace support... $ECHO_C" >&6; }
+# Check if backtrace support library is there
+have_backtrace_lib=yes
+case "$llvm_cv_os_type" in
+  FreeBSD | OpenBSD | NetBSD)
+       { echo "$as_me:$LINENO: checking for library containing backtrace" >&5
+echo $ECHO_N "checking for library containing backtrace... $ECHO_C" >&6; }
+if test "${ac_cv_search_backtrace+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_func_search_save_LIBS=$LIBS
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char backtrace ();
+int
+main ()
+{
+return backtrace ();
+  ;
+  return 0;
+}
+_ACEOF
+for ac_lib in '' execinfo; do
+  if test -z "$ac_lib"; then
+    ac_res="none required"
+  else
+    ac_res=-l$ac_lib
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+  fi
+  rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search_backtrace=$ac_res
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext \
+      conftest$ac_exeext
+  if test "${ac_cv_search_backtrace+set}" = set; then
+  break
+fi
+done
+if test "${ac_cv_search_backtrace+set}" = set; then
+  :
+else
+  ac_cv_search_backtrace=no
+fi
+rm conftest.$ac_ext
+LIBS=$ac_func_search_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_search_backtrace" >&5
+echo "${ECHO_T}$ac_cv_search_backtrace" >&6; }
+ac_res=$ac_cv_search_backtrace
+if test "$ac_res" != no; then
+  test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
+
+else
+  have_backtrace_lib=no
+fi
+ ;;
+    *) have_backtrace_lib=yes ;;
+esac
+
+# Check whether --enable-upc-backtrace was given.
+if test "${enable_upc_backtrace+set}" = set; then
+  enableval=$enable_upc_backtrace;
+  case $enableval in
+    yes | no) ;;
+    *)
+      { { echo "$as_me:$LINENO: error: --enable-upc-backtrace accepts only yes or no" >&5
+echo "$as_me: error: --enable-upc-backtrace accepts only yes or no" >&2;}
+   { (exit 1); exit 1; }; }
+  esac
+
+else
+
+  enable_upc_backtrace=yes
+
+fi
+
+{ echo "$as_me:$LINENO: result: $enable_upc_backtrace" >&5
+echo "${ECHO_T}$enable_upc_backtrace" >&6; }
+if test "$enable_upc_backtrace" = yes &&
+   test "$have_backtrace_lib" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define LIBUPC_ENABLE_BACKTRACE 1
+_ACEOF
+
+  LIBUPC_ENABLE_BACKTRACE=1
 fi
 
 
@@ -11262,7 +11406,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11265 "configure"
+#line 11409 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -23769,13 +23913,13 @@ ENABLE_CLANG_REWRITER!$ENABLE_CLANG_REWRITER$ac_delim
 ENABLE_CLANG_UPC2C!$ENABLE_CLANG_UPC2C$ac_delim
 ENABLE_CLANG_UPC_RUNTIME!$ENABLE_CLANG_UPC_RUNTIME$ac_delim
 LIBUPC_LINK_SCRIPT!$LIBUPC_LINK_SCRIPT$ac_delim
+LIBUPC_ENABLE_BACKTRACE!$LIBUPC_ENABLE_BACKTRACE$ac_delim
 ENABLE_OPTIMIZED!$ENABLE_OPTIMIZED$ac_delim
 ENABLE_PROFILING!$ENABLE_PROFILING$ac_delim
 DISABLE_ASSERTIONS!$DISABLE_ASSERTIONS$ac_delim
 ENABLE_WERROR!$ENABLE_WERROR$ac_delim
 ENABLE_EXPENSIVE_CHECKS!$ENABLE_EXPENSIVE_CHECKS$ac_delim
 EXPENSIVE_CHECKS!$EXPENSIVE_CHECKS$ac_delim
-DEBUG_RUNTIME!$DEBUG_RUNTIME$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -23817,6 +23961,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+DEBUG_RUNTIME!$DEBUG_RUNTIME$ac_delim
 DEBUG_SYMBOLS!$DEBUG_SYMBOLS$ac_delim
 KEEP_SYMBOLS!$KEEP_SYMBOLS$ac_delim
 JIT!$JIT$ac_delim
@@ -23913,7 +24058,6 @@ LLVM_DOCSDIR!$LLVM_DOCSDIR$ac_delim
 LLVM_ETCDIR!$LLVM_ETCDIR$ac_delim
 LLVM_INCLUDEDIR!$LLVM_INCLUDEDIR$ac_delim
 LLVM_INFODIR!$LLVM_INFODIR$ac_delim
-LLVM_MANDIR!$LLVM_MANDIR$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -23955,6 +24099,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+LLVM_MANDIR!$LLVM_MANDIR$ac_delim
 LLVM_CONFIGTIME!$LLVM_CONFIGTIME$ac_delim
 BINDINGS_TO_BUILD!$BINDINGS_TO_BUILD$ac_delim
 ALL_BINDINGS!$ALL_BINDINGS$ac_delim
@@ -23967,7 +24112,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 10; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 11; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
