Fix for clang-upc issue #57, fix UPC link script off/on.
CMakeLists.txt
autoconf/configure.ac
include/llvm/Config/config.h.cmake
include/llvm/Config/config.h.in
	Check and set the usage of the UPC link script.
configure
	Regenerate.
include/llvm/MC/MCObjectFileInfo.h
lib/MC/MCObjectFileInfo.cpp
	Add UPC shared section and initialize it only if linker
        script is not used.  Otherwise, linker script defines it.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -691,6 +691,7 @@ ENABLE_CLANG_STATIC_ANALYZER
 ENABLE_CLANG_REWRITER
 ENABLE_CLANG_UPC2C
 ENABLE_CLANG_UPC_RUNTIME
+LIBUPC_LINK_SCRIPT
 ENABLE_OPTIMIZED
 ENABLE_PROFILING
 DISABLE_ASSERTIONS
@@ -731,6 +732,7 @@ DATE
 FIND
 MKDIR
 MV
+LD
 RANLIB
 AR
 RM
@@ -1419,6 +1421,11 @@ Optional Features:
   --enable-clang-upc-runtime
                           Enable building of clang upc runtime (default is
                           YES)
+  --enable-upc-link-script
+                          Enable UPC's use of a custom linker script; this
+                          will define the UPC shared section as a no load
+                          section on targets where this feature is supported
+                          (requires GNU LD)
   --enable-optimized      Compile with optimizations enabled (default is NO)
   --enable-profiling      Compile with profiling enabled (default is NO)
   --enable-assertions     Compile with assertion checks enabled (default is
@@ -5361,6 +5368,59 @@ echo "$as_me: error: Invalid setting for --enable-clang-upc-runtime. Use \"yes\"
    { (exit 1); exit 1; }; } ;;
 esac
 
+{ echo "$as_me:$LINENO: checking for UPC link script support" >&5
+echo $ECHO_N "checking for UPC link script support... $ECHO_C" >&6; }
+# Check whether --enable-upc-link-script was given.
+if test "${enable_upc_link_script+set}" = set; then
+  enableval=$enable_upc_link_script;
+  case $enableval in
+  yes | no) ;;
+  *)
+    { { echo "$as_me:$LINENO: error: --enable-upc-link-script accepts only yes or no" >&5
+echo "$as_me: error: --enable-upc-link-script accepts only yes or no" >&2;}
+   { (exit 1); exit 1; }; }
+  esac
+
+else
+
+  case "$target" in
+    # disable linker script for Apple Mac OS X
+    *-*-darwin*)
+      enable_upc_link_script=no
+      ;;
+    *)
+      enable_upc_link_script=yes
+      ;;
+  esac
+
+fi
+
+if test "$enable_upc_link_script" = yes; then
+  if test "$with_gnu_ld" = yes; then
+    gen_ld_script=${srcdir}/gen-upc-ld-script.pl
+    if ! ${LD} --verbose | ${PERL} $gen_ld_script 1>/dev/null ; then
+      # if gen-upc-ld-script did not accept the output of the linker
+      # then disable UPC link script support.
+      { { echo "$as_me:$LINENO: error: selected linker does not support linker scripts" >&5
+echo "$as_me: error: selected linker does not support linker scripts" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+  fi
+fi
+{ echo "$as_me:$LINENO: result: $enable_upc_link_script" >&5
+echo "${ECHO_T}$enable_upc_link_script" >&6; }
+if test "$enable_upc_link_script" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define LIBUPC_LINK_SCRIPT 1
+_ACEOF
+
+  LIBUPC_LINK_SCRIPT=1
+else
+  LIBUPC_LINK_SCRIPT=0
+fi
+
+
 # Check whether --enable-optimized was given.
 if test "${enable_optimized+set}" = set; then
   enableval=$enable_optimized;
@@ -7019,6 +7079,47 @@ MV=$ac_cv_path_MV
 if test -n "$MV"; then
   { echo "$as_me:$LINENO: result: $MV" >&5
 echo "${ECHO_T}$MV" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+# Extract the first word of "ld", so it can be a program name with args.
+set dummy ld; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_LD+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $LD in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_LD="$LD" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_LD="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_path_LD" && ac_cv_path_LD="ld"
+  ;;
+esac
+fi
+LD=$ac_cv_path_LD
+if test -n "$LD"; then
+  { echo "$as_me:$LINENO: result: $LD" >&5
+echo "${ECHO_T}$LD" >&6; }
 else
   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
@@ -11161,7 +11262,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11164 "configure"
+#line 11265 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -23667,6 +23768,7 @@ ENABLE_CLANG_STATIC_ANALYZER!$ENABLE_CLANG_STATIC_ANALYZER$ac_delim
 ENABLE_CLANG_REWRITER!$ENABLE_CLANG_REWRITER$ac_delim
 ENABLE_CLANG_UPC2C!$ENABLE_CLANG_UPC2C$ac_delim
 ENABLE_CLANG_UPC_RUNTIME!$ENABLE_CLANG_UPC_RUNTIME$ac_delim
+LIBUPC_LINK_SCRIPT!$LIBUPC_LINK_SCRIPT$ac_delim
 ENABLE_OPTIMIZED!$ENABLE_OPTIMIZED$ac_delim
 ENABLE_PROFILING!$ENABLE_PROFILING$ac_delim
 DISABLE_ASSERTIONS!$DISABLE_ASSERTIONS$ac_delim
@@ -23674,7 +23776,6 @@ ENABLE_WERROR!$ENABLE_WERROR$ac_delim
 ENABLE_EXPENSIVE_CHECKS!$ENABLE_EXPENSIVE_CHECKS$ac_delim
 EXPENSIVE_CHECKS!$EXPENSIVE_CHECKS$ac_delim
 DEBUG_RUNTIME!$DEBUG_RUNTIME$ac_delim
-DEBUG_SYMBOLS!$DEBUG_SYMBOLS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -23716,6 +23817,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+DEBUG_SYMBOLS!$DEBUG_SYMBOLS$ac_delim
 KEEP_SYMBOLS!$KEEP_SYMBOLS$ac_delim
 JIT!$JIT$ac_delim
 TARGET_HAS_JIT!$TARGET_HAS_JIT$ac_delim
@@ -23748,6 +23850,7 @@ DATE!$DATE$ac_delim
 FIND!$FIND$ac_delim
 MKDIR!$MKDIR$ac_delim
 MV!$MV$ac_delim
+LD!$LD$ac_delim
 RANLIB!$RANLIB$ac_delim
 AR!$AR$ac_delim
 RM!$RM$ac_delim
@@ -23811,8 +23914,6 @@ LLVM_ETCDIR!$LLVM_ETCDIR$ac_delim
 LLVM_INCLUDEDIR!$LLVM_INCLUDEDIR$ac_delim
 LLVM_INFODIR!$LLVM_INFODIR$ac_delim
 LLVM_MANDIR!$LLVM_MANDIR$ac_delim
-LLVM_CONFIGTIME!$LLVM_CONFIGTIME$ac_delim
-BINDINGS_TO_BUILD!$BINDINGS_TO_BUILD$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -23854,6 +23955,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+LLVM_CONFIGTIME!$LLVM_CONFIGTIME$ac_delim
+BINDINGS_TO_BUILD!$BINDINGS_TO_BUILD$ac_delim
 ALL_BINDINGS!$ALL_BINDINGS$ac_delim
 OCAML_LIBDIR!$OCAML_LIBDIR$ac_delim
 ENABLE_VISIBILITY_INLINES_HIDDEN!$ENABLE_VISIBILITY_INLINES_HIDDEN$ac_delim
@@ -23864,7 +23967,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 8; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 10; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
