Added support of building clang-upc and clang-upc2c with configure.
	* autoconf/configure.ac
	  Add enable/disable build of UPC to C translator.
	    --enable-clang-upc2c=[yes,no]
              Configure will check if the source code for upc2c is present
	      and issue appropriate error. Default is to build it if
	      tools/clang/tools/upc2c directory is available.
	    --with-upc-pts=[packed,struct]
	    --with-upc-packed-bits=[thread,phase,vaddr]
	    --with-upc-vaddr-order=[first,last]
              Provide default values for compile options.
	* configure, Regenerate. NOTE: autoconf 2.60 and aclocal 1.9.6
	  are required.
	* Makefile.configure.in, Add support for enable/disable of
	  UPC to C translator.
	* include/llvm/Config/config.h.in, Regenerate.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -689,6 +689,7 @@ ENABLE_SPLIT_DWARF
 ENABLE_CLANG_ARCMT
 ENABLE_CLANG_STATIC_ANALYZER
 ENABLE_CLANG_REWRITER
+ENABLE_CLANG_UPC2C
 ENABLE_OPTIMIZED
 ENABLE_PROFILING
 DISABLE_ASSERTIONS
@@ -1412,6 +1413,7 @@ Optional Features:
                           Enable building of clang Static Analyzer (default is
                           YES)
   --enable-clang-rewriter Enable building of clang rewriter (default is YES)
+  --enable-clang-upc2c    Enable building of clang upc2c (default is YES)
   --enable-optimized      Compile with optimizations enabled (default is NO)
   --enable-profiling      Compile with profiling enabled (default is NO)
   --enable-assertions     Compile with assertion checks enabled (default is
@@ -1474,6 +1476,10 @@ Optional Packages:
                           resource files
   --with-c-include-dirs   Colon separated list of directories clang will
                           search for headers
+  --with-upc-pts          UPC packed or struct pointer representation.
+  --with-upc-packed-bits  UPC packed pointer representation.
+  --with-upc-pts-vaddr-order
+                          UPC vaddr first or last.
   --with-gcc-toolchain    Directory where gcc is installed.
   --with-default-sysroot  Add --sysroot=<path> to all compiler invocations.
   --with-binutils-include Specify path to binutils/include/ containing
@@ -5272,6 +5278,39 @@ echo "$as_me: error: Invalid setting for --enable-clang-rewriter. Use \"yes\" or
    { (exit 1); exit 1; }; } ;;
 esac
 
+# Check whether --enable-clang-upc2c was given.
+if test "${enable_clang_upc2c+set}" = set; then
+  enableval=$enable_clang_upc2c;
+else
+  enableval="default"
+fi
+
+UPC2CDIR="${srcdir}/tools/clang/tools/upc2c"
+case "$enableval" in
+  yes)
+    if ! test -d $UPC2CDIR; then
+      { { echo "$as_me:$LINENO: error: UPC to C translator requested but project does not exists ($UPC2CDIR). " >&5
+echo "$as_me: error: UPC to C translator requested but project does not exists ($UPC2CDIR). " >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+    ENABLE_CLANG_UPC2C=1
+ ;;
+  no)
+    ENABLE_CLANG_UPC2C=0
+ ;;
+  default)
+    if test -d $UPC2CDIR; then
+      ENABLE_CLANG_UPC2C=1
+
+    else
+      ENABLE_CLANG_UPC2C=0
+
+    fi;;
+  *) { { echo "$as_me:$LINENO: error: Invalid setting for --enable-clang-upc2c. Use \"yes\" or \"no\"" >&5
+echo "$as_me: error: Invalid setting for --enable-clang-upc2c. Use \"yes\" or \"no\"" >&2;}
+   { (exit 1); exit 1; }; } ;;
+esac
+
 # Check whether --enable-optimized was given.
 if test "${enable_optimized+set}" = set; then
   enableval=$enable_optimized;
@@ -5957,6 +5996,47 @@ fi
 
 cat >>confdefs.h <<_ACEOF
 #define C_INCLUDE_DIRS "$withval"
+_ACEOF
+
+
+# Clang UPC
+
+# Check whether --with-upc-pts was given.
+if test "${with_upc_pts+set}" = set; then
+  withval=$with_upc_pts;
+else
+  withval="packed"
+fi
+
+
+cat >>confdefs.h <<_ACEOF
+#define UPC_PTS "$withval"
+_ACEOF
+
+
+# Check whether --with-upc-packed-bits was given.
+if test "${with_upc_packed_bits+set}" = set; then
+  withval=$with_upc_packed_bits;
+else
+  withval="20,10,34"
+fi
+
+
+cat >>confdefs.h <<_ACEOF
+#define UPC_PACKED_BITS "$withval"
+_ACEOF
+
+
+# Check whether --with-upc-pts-vaddr-order was given.
+if test "${with_upc_pts_vaddr_order+set}" = set; then
+  withval=$with_upc_pts_vaddr_order;
+else
+  withval="first"
+fi
+
+
+cat >>confdefs.h <<_ACEOF
+#define UPC_PTS_VADDR_ORDER "$withval"
 _ACEOF
 
 
@@ -8825,7 +8905,9 @@ if test "${enable_ltdl_install+set}" = set; then
 fi
 
 
- if test x"${enable_ltdl_install-no}" != xno; then
+
+
+if test x"${enable_ltdl_install-no}" != xno; then
   INSTALL_LTDL_TRUE=
   INSTALL_LTDL_FALSE='#'
 else
@@ -8833,7 +8915,9 @@ else
   INSTALL_LTDL_FALSE=
 fi
 
- if test x"${enable_ltdl_convenience-no}" != xno; then
+
+
+if test x"${enable_ltdl_convenience-no}" != xno; then
   CONVENIENCE_LTDL_TRUE=
   CONVENIENCE_LTDL_FALSE='#'
 else
@@ -10582,7 +10666,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10585 "configure"
+#line 10669 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -23086,6 +23170,7 @@ ENABLE_SPLIT_DWARF!$ENABLE_SPLIT_DWARF$ac_delim
 ENABLE_CLANG_ARCMT!$ENABLE_CLANG_ARCMT$ac_delim
 ENABLE_CLANG_STATIC_ANALYZER!$ENABLE_CLANG_STATIC_ANALYZER$ac_delim
 ENABLE_CLANG_REWRITER!$ENABLE_CLANG_REWRITER$ac_delim
+ENABLE_CLANG_UPC2C!$ENABLE_CLANG_UPC2C$ac_delim
 ENABLE_OPTIMIZED!$ENABLE_OPTIMIZED$ac_delim
 ENABLE_PROFILING!$ENABLE_PROFILING$ac_delim
 DISABLE_ASSERTIONS!$DISABLE_ASSERTIONS$ac_delim
@@ -23095,7 +23180,6 @@ EXPENSIVE_CHECKS!$EXPENSIVE_CHECKS$ac_delim
 DEBUG_RUNTIME!$DEBUG_RUNTIME$ac_delim
 DEBUG_SYMBOLS!$DEBUG_SYMBOLS$ac_delim
 KEEP_SYMBOLS!$KEEP_SYMBOLS$ac_delim
-JIT!$JIT$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -23137,6 +23221,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+JIT!$JIT$ac_delim
 TARGET_HAS_JIT!$TARGET_HAS_JIT$ac_delim
 ENABLE_DOCS!$ENABLE_DOCS$ac_delim
 ENABLE_DOXYGEN!$ENABLE_DOXYGEN$ac_delim
@@ -23233,7 +23318,6 @@ LLVM_MANDIR!$LLVM_MANDIR$ac_delim
 LLVM_CONFIGTIME!$LLVM_CONFIGTIME$ac_delim
 BINDINGS_TO_BUILD!$BINDINGS_TO_BUILD$ac_delim
 ALL_BINDINGS!$ALL_BINDINGS$ac_delim
-OCAML_LIBDIR!$OCAML_LIBDIR$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -23275,6 +23359,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+OCAML_LIBDIR!$OCAML_LIBDIR$ac_delim
 ENABLE_VISIBILITY_INLINES_HIDDEN!$ENABLE_VISIBILITY_INLINES_HIDDEN$ac_delim
 RPATH!$RPATH$ac_delim
 RDYNAMIC!$RDYNAMIC$ac_delim
@@ -23283,7 +23368,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 6; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 7; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
