dd configuration/Makefile for UPC backtrace on systems that require execinfo library (BSD).

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -691,8 +691,6 @@ ENABLE_CLANG_STATIC_ANALYZER
 ENABLE_CLANG_REWRITER
 ENABLE_CLANG_UPC2C
 ENABLE_CLANG_UPC_RUNTIME
-LIBUPC_LINK_SCRIPT
-LIBUPC_ENABLE_BACKTRACE
 ENABLE_OPTIMIZED
 ENABLE_PROFILING
 DISABLE_ASSERTIONS
@@ -722,6 +720,8 @@ OPTIMIZE_OPTION
 EXTRA_OPTIONS
 EXTRA_LD_OPTIONS
 CLANG_SRC_ROOT
+LIBUPC_LINK_SCRIPT
+LIBUPC_ENABLE_BACKTRACE
 BINUTILS_INCDIR
 INTERNAL_PREFIX
 NM
@@ -1422,14 +1422,6 @@ Optional Features:
   --enable-clang-upc-runtime
                           Enable building of clang upc runtime (default is
                           YES)
-  --enable-upc-link-script
-                          Enable UPC's use of a custom linker script; this
-                          will define the UPC shared section as a no load
-                          section on targets where this feature is supported
-                          (requires GNU LD)
-  --enable-upc-backtrace  Enable UPC backtrace; Enable stack frame backtrace
-                          report when UPC run-time fatal errors occur or by
-                          user request (via signal)
   --enable-optimized      Compile with optimizations enabled (default is NO)
   --enable-profiling      Compile with profiling enabled (default is NO)
   --enable-assertions     Compile with assertion checks enabled (default is
@@ -1472,6 +1464,14 @@ Optional Features:
                           target1,target2,... (default=disable)
   --enable-bindings       Build specific language bindings:
                           all,auto,none,{binding-name} (default=auto)
+  --enable-upc-link-script
+                          Enable UPC's use of a custom linker script; this
+                          will define the UPC shared section as a no load
+                          section on targets where this feature is supported
+                          (requires GNU LD)
+  --enable-upc-backtrace  Enable UPC backtrace; Enable stack frame backtrace
+                          report when UPC run-time fatal errors occur or by
+                          user request (via signal)
   --enable-terminfo       Query the terminfo database if available (default is
                           YES)
   --enable-libffi         Check for the presence of libffi (default is NO)
@@ -1492,6 +1492,10 @@ Optional Packages:
                           resource files
   --with-c-include-dirs   Colon separated list of directories clang will
                           search for headers
+  --with-execinfo-lib-path
+                          Specify path for execinfo library
+  --with-execinfo-inc-path
+                          Specify path for execinfo include
   --with-upc-pts          UPC packed or struct pointer representation.
   --with-upc-pts-packed-bits
                           UPC packed pointer representation.
@@ -5372,199 +5376,6 @@ echo "$as_me: error: Invalid setting for --enable-clang-upc-runtime. Use \"yes\"
    { (exit 1); exit 1; }; } ;;
 esac
 
-{ echo "$as_me:$LINENO: checking for UPC link script support" >&5
-echo $ECHO_N "checking for UPC link script support... $ECHO_C" >&6; }
-# Check whether --enable-upc-link-script was given.
-if test "${enable_upc_link_script+set}" = set; then
-  enableval=$enable_upc_link_script;
-  case $enableval in
-  yes | no) ;;
-  *)
-    { { echo "$as_me:$LINENO: error: --enable-upc-link-script accepts only yes or no" >&5
-echo "$as_me: error: --enable-upc-link-script accepts only yes or no" >&2;}
-   { (exit 1); exit 1; }; }
-  esac
-
-else
-
-  case "$target" in
-    # disable linker script for Apple Mac OS X
-    *-*-darwin*)
-      enable_upc_link_script=no
-      ;;
-    *)
-      enable_upc_link_script=yes
-      ;;
-  esac
-
-fi
-
-if test "$enable_upc_link_script" = yes; then
-  if test "$with_gnu_ld" = yes; then
-    gen_ld_script=${srcdir}/gen-upc-ld-script.pl
-    if ! ${LD} --verbose | ${PERL} $gen_ld_script 1>/dev/null ; then
-      # if gen-upc-ld-script did not accept the output of the linker
-      # then disable UPC link script support.
-      { { echo "$as_me:$LINENO: error: selected linker does not support linker scripts" >&5
-echo "$as_me: error: selected linker does not support linker scripts" >&2;}
-   { (exit 1); exit 1; }; }
-    fi
-  fi
-fi
-{ echo "$as_me:$LINENO: result: $enable_upc_link_script" >&5
-echo "${ECHO_T}$enable_upc_link_script" >&6; }
-if test "$enable_upc_link_script" = yes; then
-
-cat >>confdefs.h <<\_ACEOF
-#define LIBUPC_LINK_SCRIPT 1
-_ACEOF
-
-  LIBUPC_LINK_SCRIPT=1
-else
-  LIBUPC_LINK_SCRIPT=0
-fi
-
-
-{ echo "$as_me:$LINENO: checking for UPC backtrace support" >&5
-echo $ECHO_N "checking for UPC backtrace support... $ECHO_C" >&6; }
-# Check if backtrace support library is there
-have_backtrace_lib=yes
-case "$llvm_cv_os_type" in
-  FreeBSD | OpenBSD | NetBSD)
-       { echo "$as_me:$LINENO: checking for library containing backtrace" >&5
-echo $ECHO_N "checking for library containing backtrace... $ECHO_C" >&6; }
-if test "${ac_cv_search_backtrace+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_func_search_save_LIBS=$LIBS
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-char backtrace ();
-int
-main ()
-{
-return backtrace ();
-  ;
-  return 0;
-}
-_ACEOF
-for ac_lib in '' execinfo; do
-  if test -z "$ac_lib"; then
-    ac_res="none required"
-  else
-    ac_res=-l$ac_lib
-    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
-  fi
-  rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
-  { (case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_try") 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_try") 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_search_backtrace=$ac_res
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-
-fi
-
-rm -f core conftest.err conftest.$ac_objext \
-      conftest$ac_exeext
-  if test "${ac_cv_search_backtrace+set}" = set; then
-  break
-fi
-done
-if test "${ac_cv_search_backtrace+set}" = set; then
-  :
-else
-  ac_cv_search_backtrace=no
-fi
-rm conftest.$ac_ext
-LIBS=$ac_func_search_save_LIBS
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_search_backtrace" >&5
-echo "${ECHO_T}$ac_cv_search_backtrace" >&6; }
-ac_res=$ac_cv_search_backtrace
-if test "$ac_res" != no; then
-  test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
-
-else
-  have_backtrace_lib=no
-fi
- ;;
-    *) have_backtrace_lib=yes ;;
-esac
-
-# Check whether --enable-upc-backtrace was given.
-if test "${enable_upc_backtrace+set}" = set; then
-  enableval=$enable_upc_backtrace;
-  case $enableval in
-    yes | no) ;;
-    *)
-      { { echo "$as_me:$LINENO: error: --enable-upc-backtrace accepts only yes or no" >&5
-echo "$as_me: error: --enable-upc-backtrace accepts only yes or no" >&2;}
-   { (exit 1); exit 1; }; }
-  esac
-
-else
-
-  enable_upc_backtrace=yes
-
-fi
-
-{ echo "$as_me:$LINENO: result: $enable_upc_backtrace" >&5
-echo "${ECHO_T}$enable_upc_backtrace" >&6; }
-if test "$enable_upc_backtrace" = yes &&
-   test "$have_backtrace_lib" = yes; then
-
-cat >>confdefs.h <<\_ACEOF
-#define LIBUPC_ENABLE_BACKTRACE 1
-_ACEOF
-
-  LIBUPC_ENABLE_BACKTRACE=1
-fi
-
-
 # Check whether --enable-optimized was given.
 if test "${enable_optimized+set}" = set; then
   enableval=$enable_optimized;
@@ -6253,7 +6064,228 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 
-# Clang UPC
+{ echo "$as_me:$LINENO: checking for UPC link script support" >&5
+echo $ECHO_N "checking for UPC link script support... $ECHO_C" >&6; }
+# Check whether --enable-upc-link-script was given.
+if test "${enable_upc_link_script+set}" = set; then
+  enableval=$enable_upc_link_script;
+  case $enableval in
+  yes | no) ;;
+  *)
+    { { echo "$as_me:$LINENO: error: --enable-upc-link-script accepts only yes or no" >&5
+echo "$as_me: error: --enable-upc-link-script accepts only yes or no" >&2;}
+   { (exit 1); exit 1; }; }
+  esac
+
+else
+
+  case "$target" in
+    # disable linker script for Apple Mac OS X
+    *-*-darwin*)
+      enable_upc_link_script=no
+      ;;
+    *)
+      enable_upc_link_script=yes
+      ;;
+  esac
+
+fi
+
+if test "$enable_upc_link_script" = yes; then
+  if test "$with_gnu_ld" = yes; then
+    gen_ld_script=${srcdir}/gen-upc-ld-script.pl
+    if ! ${LD} --verbose | ${PERL} $gen_ld_script 1>/dev/null ; then
+      # if gen-upc-ld-script did not accept the output of the linker
+      # then disable UPC link script support.
+      { { echo "$as_me:$LINENO: error: selected linker does not support linker scripts" >&5
+echo "$as_me: error: selected linker does not support linker scripts" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+  fi
+fi
+{ echo "$as_me:$LINENO: result: $enable_upc_link_script" >&5
+echo "${ECHO_T}$enable_upc_link_script" >&6; }
+if test "$enable_upc_link_script" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define LIBUPC_LINK_SCRIPT 1
+_ACEOF
+
+  LIBUPC_LINK_SCRIPT=1
+else
+  LIBUPC_LINK_SCRIPT=0
+fi
+
+
+
+# Check whether --with-execinfo-lib-path was given.
+if test "${with_execinfo_lib_path+set}" = set; then
+  withval=$with_execinfo_lib_path;
+else
+  withval=none
+fi
+
+{ echo "$as_me:$LINENO: checking execinfo lib path" >&5
+echo $ECHO_N "checking execinfo lib path... $ECHO_C" >&6; }
+case "$withval" in
+  none) ;;
+  *)
+     execinfo_lib_path="$withval" ;;
+esac
+{ echo "$as_me:$LINENO: result: $execinfo_lib_path" >&5
+echo "${ECHO_T}$execinfo_lib_path" >&6; }
+
+
+# Check whether --with-execinfo-inc-path was given.
+if test "${with_execinfo_inc_path+set}" = set; then
+  withval=$with_execinfo_inc_path;
+else
+  withval=none
+fi
+
+{ echo "$as_me:$LINENO: checking execinfo inc path" >&5
+echo $ECHO_N "checking execinfo inc path... $ECHO_C" >&6; }
+case "$withval" in
+  none) ;;
+  *)
+     execinfo_inc_path="$withval" ;;
+esac
+{ echo "$as_me:$LINENO: result: $execinfo_inc_path" >&5
+echo "${ECHO_T}$execinfo_inc_path" >&6; }
+
+save_CFLAGS="$CFLAGS"
+ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+if test "x$execinfo_inc_path" != x ; then
+  CFLAGS="$CFLAGS -I$execinfo_inc_path"
+fi
+if test "x$execinfo_lib_path" != x ; then
+  CFLAGS="$CFLAGS -L$execinfo_lib_path"
+fi
+case "$llvm_cv_os_type" in
+  FreeBSD|OpenBSD|NetBSD) CFLAGS="$CFLAGS -lexecinfo" ;;
+  *) ;;
+esac
+cat >conftest.$ac_ext <<_ACEOF
+
+  /* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+    #include <execinfo.h>
+    int main () {
+      void *p;
+      return backtrace(&p, 1);
+    }
+
+
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  have_backtrace=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	have_backtrace=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+CFLAGS="$save_CFLAGS"
+
+{ echo "$as_me:$LINENO: checking for UPC backtrace support" >&5
+echo $ECHO_N "checking for UPC backtrace support... $ECHO_C" >&6; }
+# Check whether --enable-upc-backtrace was given.
+if test "${enable_upc_backtrace+set}" = set; then
+  enableval=$enable_upc_backtrace;
+  case $enableval in
+    yes | no) ;;
+    *)
+      { { echo "$as_me:$LINENO: error: --enable-upc-backtrace accepts only yes or no" >&5
+echo "$as_me: error: --enable-upc-backtrace accepts only yes or no" >&2;}
+   { (exit 1); exit 1; }; }
+  esac
+
+else
+
+  enable_upc_backtrace=yes
+
+fi
+
+if test "x$enable_upc_backtrace" = xyes &&
+   test "x$have_backtrace" = xyes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define LIBUPC_ENABLE_BACKTRACE 1
+_ACEOF
+
+  LIBUPC_ENABLE_BACKTRACE=1
+  if test "x$execinfo_lib_path" != x ; then
+
+cat >>confdefs.h <<_ACEOF
+#define LIBUPC_EXECINFO_LIB_PATH "$execinfo_lib_path"
+_ACEOF
+
+  fi
+  if test "x$execinfo_inc_path" != x ; then
+
+cat >>confdefs.h <<_ACEOF
+#define LIBUPC_EXECINFO_INC_PATH "$execinfo_inc_path"
+_ACEOF
+
+  fi
+else
+  enable_upc_backtrace=no
+fi
+{ echo "$as_me:$LINENO: result: $enable_upc_backtrace" >&5
+echo "${ECHO_T}$enable_upc_backtrace" >&6; }
+
+
 
 # Check whether --with-upc-pts was given.
 if test "${with_upc_pts+set}" = set; then
@@ -6294,7 +6326,6 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 
-# Check for runtime model
 { echo "$as_me:$LINENO: checking for UPC runtime model" >&5
 echo $ECHO_N "checking for UPC runtime model... $ECHO_C" >&6; }
 
@@ -6326,7 +6357,6 @@ fi
 { echo "$as_me:$LINENO: result: $upc_runtime_model" >&5
 echo "${ECHO_T}$upc_runtime_model" >&6; }
 
-# Additional checks in case of Portals4
 if test "$upc_runtime_model" = "portals4"; then
 
 for ac_header in portals4.h
@@ -6733,7 +6763,6 @@ _ACEOF
   fi
 fi
 
-# Check for Clang UPC runtime configuration
 if test "$llvm_cv_clang_upc_runtime" -eq "1" ; then
   subdirs="$subdirs tools/clang/runtime/libupc"
 
@@ -11406,7 +11435,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11409 "configure"
+#line 11438 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -23912,14 +23941,14 @@ ENABLE_CLANG_STATIC_ANALYZER!$ENABLE_CLANG_STATIC_ANALYZER$ac_delim
 ENABLE_CLANG_REWRITER!$ENABLE_CLANG_REWRITER$ac_delim
 ENABLE_CLANG_UPC2C!$ENABLE_CLANG_UPC2C$ac_delim
 ENABLE_CLANG_UPC_RUNTIME!$ENABLE_CLANG_UPC_RUNTIME$ac_delim
-LIBUPC_LINK_SCRIPT!$LIBUPC_LINK_SCRIPT$ac_delim
-LIBUPC_ENABLE_BACKTRACE!$LIBUPC_ENABLE_BACKTRACE$ac_delim
 ENABLE_OPTIMIZED!$ENABLE_OPTIMIZED$ac_delim
 ENABLE_PROFILING!$ENABLE_PROFILING$ac_delim
 DISABLE_ASSERTIONS!$DISABLE_ASSERTIONS$ac_delim
 ENABLE_WERROR!$ENABLE_WERROR$ac_delim
 ENABLE_EXPENSIVE_CHECKS!$ENABLE_EXPENSIVE_CHECKS$ac_delim
 EXPENSIVE_CHECKS!$EXPENSIVE_CHECKS$ac_delim
+DEBUG_RUNTIME!$DEBUG_RUNTIME$ac_delim
+DEBUG_SYMBOLS!$DEBUG_SYMBOLS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -23961,8 +23990,6 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
-DEBUG_RUNTIME!$DEBUG_RUNTIME$ac_delim
-DEBUG_SYMBOLS!$DEBUG_SYMBOLS$ac_delim
 KEEP_SYMBOLS!$KEEP_SYMBOLS$ac_delim
 JIT!$JIT$ac_delim
 TARGET_HAS_JIT!$TARGET_HAS_JIT$ac_delim
@@ -23984,6 +24011,8 @@ OPTIMIZE_OPTION!$OPTIMIZE_OPTION$ac_delim
 EXTRA_OPTIONS!$EXTRA_OPTIONS$ac_delim
 EXTRA_LD_OPTIONS!$EXTRA_LD_OPTIONS$ac_delim
 CLANG_SRC_ROOT!$CLANG_SRC_ROOT$ac_delim
+LIBUPC_LINK_SCRIPT!$LIBUPC_LINK_SCRIPT$ac_delim
+LIBUPC_ENABLE_BACKTRACE!$LIBUPC_ENABLE_BACKTRACE$ac_delim
 BINUTILS_INCDIR!$BINUTILS_INCDIR$ac_delim
 INTERNAL_PREFIX!$INTERNAL_PREFIX$ac_delim
 NM!$NM$ac_delim
